//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BotTelegram.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class AbpEdition
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AbpEdition()
        {
            this.AbpFeatures = new HashSet<AbpFeature>();
            this.AbpTenants = new HashSet<AbpTenant>();
            this.AppSubscriptionPayments = new HashSet<AppSubscriptionPayment>();
        }
    
        public int Id { get; set; }
        public System.DateTime CreationTime { get; set; }
        public Nullable<long> CreatorUserId { get; set; }
        public Nullable<long> DeleterUserId { get; set; }
        public Nullable<System.DateTime> DeletionTime { get; set; }
        public string DisplayName { get; set; }
        public bool IsDeleted { get; set; }
        public Nullable<System.DateTime> LastModificationTime { get; set; }
        public Nullable<long> LastModifierUserId { get; set; }
        public string Name { get; set; }
        public string Discriminator { get; set; }
        public Nullable<decimal> AnnualPrice { get; set; }
        public Nullable<int> ExpiringEditionId { get; set; }
        public Nullable<decimal> MonthlyPrice { get; set; }
        public Nullable<int> TrialDayCount { get; set; }
        public Nullable<int> WaitingDayAfterExpire { get; set; }
        public Nullable<decimal> DailyPrice { get; set; }
        public Nullable<decimal> WeeklyPrice { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AbpFeature> AbpFeatures { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AbpTenant> AbpTenants { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AppSubscriptionPayment> AppSubscriptionPayments { get; set; }
    }
}
