//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BotTelegram.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class AbpWebhookEvent
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AbpWebhookEvent()
        {
            this.AbpWebhookSendAttempts = new HashSet<AbpWebhookSendAttempt>();
        }
    
        public System.Guid Id { get; set; }
        public string WebhookName { get; set; }
        public string Data { get; set; }
        public System.DateTime CreationTime { get; set; }
        public Nullable<int> TenantId { get; set; }
        public bool IsDeleted { get; set; }
        public Nullable<System.DateTime> DeletionTime { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AbpWebhookSendAttempt> AbpWebhookSendAttempts { get; set; }
    }
}
