//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BotTelegram.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class AbpWebhookSubscription
    {
        public System.Guid Id { get; set; }
        public System.DateTime CreationTime { get; set; }
        public Nullable<long> CreatorUserId { get; set; }
        public Nullable<int> TenantId { get; set; }
        public string WebhookUri { get; set; }
        public string Secret { get; set; }
        public bool IsActive { get; set; }
        public string Webhooks { get; set; }
        public string Headers { get; set; }
    }
}
