//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BotTelegram.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class AppBinaryObject
    {
        public System.Guid Id { get; set; }
        public byte[] Bytes { get; set; }
        public Nullable<int> TenantId { get; set; }
    }
}
