//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BotTelegram.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class AppSubscriptionPayment
    {
        public long Id { get; set; }
        public decimal Amount { get; set; }
        public System.DateTime CreationTime { get; set; }
        public Nullable<long> CreatorUserId { get; set; }
        public int DayCount { get; set; }
        public Nullable<long> DeleterUserId { get; set; }
        public Nullable<System.DateTime> DeletionTime { get; set; }
        public int EditionId { get; set; }
        public int Gateway { get; set; }
        public bool IsDeleted { get; set; }
        public Nullable<System.DateTime> LastModificationTime { get; set; }
        public Nullable<long> LastModifierUserId { get; set; }
        public string SuccessUrl { get; set; }
        public Nullable<int> PaymentPeriodType { get; set; }
        public int Status { get; set; }
        public int TenantId { get; set; }
        public string InvoiceNo { get; set; }
        public string Description { get; set; }
        public string ErrorUrl { get; set; }
        public string ExternalPaymentId { get; set; }
        public bool IsRecurring { get; set; }
        public int EditionPaymentType { get; set; }
    
        public virtual AbpEdition AbpEdition { get; set; }
    }
}
