//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BotTelegram.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class BuyPincodeTransaction
    {
        public long Id { get; set; }
        public string InvoiceCode { get; set; }
        public Nullable<byte> InvoiceType { get; set; }
        public string TransCode { get; set; }
        public Nullable<System.DateTime> CreatedTime { get; set; }
        public Nullable<int> ProductId { get; set; }
        public Nullable<byte> CardType { get; set; }
        public int CardAmount { get; set; }
        public Nullable<int> Quantity { get; set; }
        public string RequestIpAddress { get; set; }
        public Nullable<byte> Status { get; set; }
        public string PartnerCode { get; set; }
        public Nullable<int> PartnerDiscountPolicyId { get; set; }
        public Nullable<decimal> PartnerDiscountPolicyDiscountPercentage { get; set; }
        public Nullable<decimal> PartnerSaleAmount { get; set; }
        public string ProviderCode { get; set; }
        public Nullable<int> ProviderDiscountPolicyId { get; set; }
        public Nullable<decimal> ProviderDiscountPolicyDiscountPercentage { get; set; }
        public Nullable<decimal> ProviderPartnerSaleAmount { get; set; }
        public string ProviderRequestTransCode { get; set; }
        public string ProviderResponseTransCode { get; set; }
        public string ProviderResponseCode { get; set; }
        public string ProviderResponseMessage { get; set; }
        public string TrippdesKey { get; set; }
        public Nullable<long> SaleInvoiceId { get; set; }
    }
}
