//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BotTelegram.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class CaptchaFile
    {
        public long Id { get; set; }
        public string Account { get; set; }
        public string CaptchaName { get; set; }
        public string CaptchaText { get; set; }
        public Nullable<byte> Status { get; set; }
        public Nullable<System.DateTime> CreatedTime { get; set; }
    }
}
