//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BotTelegram.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChargingTopupTransactionHistory
    {
        public long Id { get; set; }
        public Nullable<long> SaleInvoiceId { get; set; }
        public Nullable<byte> TelcoId { get; set; }
        public Nullable<long> PartnerChargingTransactionId { get; set; }
        public string PartnerChargingTranscode { get; set; }
        public string CardCode { get; set; }
        public string CardSerial { get; set; }
        public string Mobile { get; set; }
        public Nullable<System.DateTime> CreatedTime { get; set; }
        public Nullable<System.DateTime> StartProcessTime { get; set; }
        public Nullable<System.DateTime> EndProcessTime { get; set; }
        public Nullable<int> RequestCardAmount { get; set; }
        public Nullable<int> CardAmount { get; set; }
        public Nullable<byte> Status { get; set; }
        public string Response { get; set; }
        public Nullable<bool> IsReCalculate { get; set; }
        public Nullable<int> BeforeBalance { get; set; }
        public Nullable<int> AfterBalance { get; set; }
        public Nullable<int> BeforeDebt { get; set; }
        public Nullable<int> AfterDebt { get; set; }
        public string WorkerId { get; set; }
        public Nullable<byte> PaidType { get; set; }
        public string SimId { get; set; }
        public string SimNo { get; set; }
        public Nullable<byte> RetryCount { get; set; }
        public Nullable<int> Fee { get; set; }
        public Nullable<byte> SourceInvoiceType { get; set; }
        public string Info { get; set; }
    }
}
