//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BotTelegram.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChargingPartnerProviderConfig
    {
        public int Id { get; set; }
        public Nullable<int> CardAmount { get; set; }
        public Nullable<byte> CardType { get; set; }
        public string PartnerCode { get; set; }
        public string ProviderCode { get; set; }
        public Nullable<bool> IsEnable { get; set; }
        public Nullable<bool> IsEnablePayExpress { get; set; }
        public Nullable<int> WaitPayExpressTime { get; set; }
        public Nullable<bool> IsEnablePartnerChargingTopup { get; set; }
        public Nullable<int> PartnerChargingTopupWaitTimeInSecond { get; set; }
        public Nullable<bool> IsEnableSaleInvoiceSlowTopup { get; set; }
        public Nullable<int> SaleInvoiceSlowTopupWaitTimeInSecond { get; set; }
        public Nullable<bool> IsEnableSaleInvoiceModemCharge { get; set; }
        public Nullable<int> SaleInvoiceModemChargeWaitTimeInSecond { get; set; }
        public int LoadingCapacity { get; set; }
        public Nullable<int> TenantId { get; set; }
        public System.DateTime CreationTime { get; set; }
        public Nullable<long> CreatorUserId { get; set; }
        public Nullable<System.DateTime> LastModificationTime { get; set; }
        public Nullable<long> LastModifierUserId { get; set; }
        public Nullable<bool> IsEnableSpecialPrioritySaleInvoiceSlowTopup { get; set; }
        public Nullable<int> FromCardAmount { get; set; }
        public Nullable<int> ToCardAmount { get; set; }
    }
}
