//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BotTelegram.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class CheckCardTransaction
    {
        public long Id { get; set; }
        public Nullable<System.DateTime> CreatedTime { get; set; }
        public string CardSerial { get; set; }
        public string CardCode { get; set; }
        public Nullable<byte> CardType { get; set; }
        public Nullable<byte> Status { get; set; }
        public Nullable<byte> CardStatus { get; set; }
        public Nullable<System.DateTime> UseTime { get; set; }
        public Nullable<System.DateTime> ExpiredTime { get; set; }
        public string Info { get; set; }
        public string Account { get; set; }
        public string AppInfo { get; set; }
        public Nullable<int> CardAmount { get; set; }
        public string Isdn { get; set; }
        public string WorkerChannel { get; set; }
        public Nullable<int> CheckCount { get; set; }
        public Nullable<bool> IsProcessed { get; set; }
        public string UniqueCardSerial { get; set; }
    }
}
