//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BotTelegram.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class DepositPartnerInvoice
    {
        public long Id { get; set; }
        public string Code { get; set; }
        public int PartnerId { get; set; }
        public long CreatedByUserId { get; set; }
        public decimal MoneyAmount { get; set; }
        public byte Status { get; set; }
        public System.DateTime CreatedTime { get; set; }
        public byte Type { get; set; }
        public string RefSourceMoneyInvoice { get; set; }
        public string RefSourceCustomerAccountNo { get; set; }
        public string RefSourceCustomerAccountName { get; set; }
        public int SourceMoneyId { get; set; }
        public string Note { get; set; }
    }
}
