//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BotTelegram.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class InvoiceTypeTelcoChargingConfig
    {
        public int Id { get; set; }
        public string InvoiceTypeCode { get; set; }
        public Nullable<byte> TelcoId { get; set; }
        public Nullable<byte> Status { get; set; }
        public Nullable<byte> PaidType { get; set; }
        public Nullable<int> FromAmount { get; set; }
        public Nullable<int> ToAmount { get; set; }
        public string Note { get; set; }
        public Nullable<int> OrderProcessing { get; set; }
        public Nullable<byte> Code { get; set; }
    }
}
