//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BotTelegram.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class JobSchedule
    {
        public string JobName { get; set; }
        public Nullable<System.DateTime> LastTime { get; set; }
        public Nullable<long> LastId { get; set; }
        public System.DateTime LastRun { get; set; }
    }
}
