//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BotTelegram.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class MaintainSM
    {
        public int ID { get; set; }
        public string SimNumber { get; set; }
        public string ReceiverNumber { get; set; }
        public string SmsContent { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public Nullable<bool> SentStatus { get; set; }
    }
}
