//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BotTelegram.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class MerchantUserDepositTransaction
    {
        public long Id { get; set; }
        public string Code { get; set; }
        public Nullable<System.DateTime> CreatedTime { get; set; }
        public string ProviderTransactionId { get; set; }
        public string ProviderTransactionTime { get; set; }
        public Nullable<int> Amount { get; set; }
        public string TransactionMessage { get; set; }
        public string MerchantId { get; set; }
        public string Sender { get; set; }
        public string Checksum { get; set; }
        public string PartnerCode { get; set; }
        public string Receiver { get; set; }
        public Nullable<byte> Type { get; set; }
        public Nullable<byte> SourceMoney { get; set; }
        public Nullable<byte> Status { get; set; }
        public Nullable<bool> IsCallbackPartner { get; set; }
        public Nullable<System.DateTime> CallbackTime { get; set; }
        public string ProviderCode { get; set; }
        public string ServiceCode { get; set; }
    }
}
