//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BotTelegram.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class MobiFoneToken
    {
        public int Id { get; set; }
        public string DeviceId { get; set; }
        public string Msisdn { get; set; }
        public string Otp { get; set; }
        public string Token { get; set; }
        public string RefreshKey { get; set; }
        public Nullable<System.DateTime> CreatedTime { get; set; }
        public Nullable<byte> Status { get; set; }
        public Nullable<int> MobiFoneUserId { get; set; }
        public Nullable<System.DateTime> NextProcessTime { get; set; }
        public Nullable<int> TryCount { get; set; }
    }
}
