//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BotTelegram.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ModemChargingActiveSimHistory
    {
        public long Id { get; set; }
        public Nullable<long> UserId { get; set; }
        public string Mobile { get; set; }
        public Nullable<byte> TelcoId { get; set; }
        public Nullable<byte> PaidType { get; set; }
        public Nullable<int> Balance { get; set; }
        public Nullable<System.DateTime> LastUpdateTime { get; set; }
    }
}
