//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BotTelegram.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class PartnerTopupTransactionConfigMaxWaiting
    {
        public int Id { get; set; }
        public string PartnerCode { get; set; }
        public string ProviderCode { get; set; }
        public Nullable<byte> Priority { get; set; }
        public Nullable<int> ProductId { get; set; }
        public Nullable<byte> TelcoId { get; set; }
        public Nullable<int> FromAmount { get; set; }
        public Nullable<int> ToAmount { get; set; }
        public Nullable<int> MaxWaitingTopupTransaction { get; set; }
        public Nullable<byte> Status { get; set; }
        public Nullable<int> PayExpressWaitTime { get; set; }
        public Nullable<int> CancelTimeInSecond { get; set; }
        public bool IsEnablePrepaid { get; set; }
        public bool IsEnablePostpaid { get; set; }
        public bool IsAlowExtend { get; set; }
        public Nullable<int> ExtendTimeInSec { get; set; }
        public Nullable<int> MinCardValue { get; set; }
        public bool IsEnableChangeProvider { get; set; }
        public string ChangeToProvider { get; set; }
        public int ChangeProviderTimeInSecond { get; set; }
        public bool IsSplitAmount { get; set; }
        public Nullable<int> TenantId { get; set; }
        public System.DateTime CreationTime { get; set; }
        public Nullable<long> CreatorUserId { get; set; }
        public Nullable<System.DateTime> LastModificationTime { get; set; }
        public Nullable<long> LastModifierUserId { get; set; }
        public byte PaidType { get; set; }
        public Nullable<bool> IsDefault { get; set; }
        public Nullable<int> MaxWaitingByDefault { get; set; }
    }
}
