//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BotTelegram.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Partner
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Code { get; set; }
        public string Password { get; set; }
        public string AllowIps { get; set; }
        public string Phone { get; set; }
        public Nullable<short> Status { get; set; }
        public bool IsEnableCallback { get; set; }
        public string Webhook { get; set; }
        public bool IsEnableTelegramNoti { get; set; }
        public string TelegramSuportGroupId { get; set; }
        public int TopupPriority { get; set; }
        public Nullable<int> DeltaSecCheckProcessingTransaction { get; set; }
        public Nullable<System.DateTime> LastTimeChecked { get; set; }
        public bool IsAlwayReturnRealCardAmount { get; set; }
        public Nullable<int> TenantId { get; set; }
        public System.DateTime CreationTime { get; set; }
        public Nullable<long> CreatorUserId { get; set; }
        public Nullable<System.DateTime> LastModificationTime { get; set; }
        public Nullable<long> LastModifierUserId { get; set; }
        public string ProviderMerchantId { get; set; }
        public Nullable<long> UserId { get; set; }
        public string Logo { get; set; }
        public string DepositUrlCallback { get; set; }
        public Nullable<bool> IsPartnerDecideCancelTopupTransaction { get; set; }
        public Nullable<bool> IsFixTopupTransactionExpireTime { get; set; }
        public Nullable<int> TopupTransactionExpireTimeInSec { get; set; }
        public string WebhookFastChargingTopup { get; set; }
    }
}
