//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BotTelegram.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class PartnerUserPartner
    {
        public int Id { get; set; }
        public Nullable<int> PartnerUserId { get; set; }
        public Nullable<int> PartnerId { get; set; }
        public Nullable<System.DateTime> CreatedTime { get; set; }
        public Nullable<byte> Status { get; set; }
    }
}
