//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BotTelegram.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DevPayExpressEntities : DbContext
    {
        public DevPayExpressEntities()
            : base("name=DevPayExpressEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<C__EFMigrationsHistory> C__EFMigrationsHistory { get; set; }
        public virtual DbSet<AbpAuditLog> AbpAuditLogs { get; set; }
        public virtual DbSet<AbpBackgroundJob> AbpBackgroundJobs { get; set; }
        public virtual DbSet<AbpEdition> AbpEditions { get; set; }
        public virtual DbSet<AbpEntityChanx> AbpEntityChanges { get; set; }
        public virtual DbSet<AbpEntityChangeSet> AbpEntityChangeSets { get; set; }
        public virtual DbSet<AbpEntityPropertyChanx> AbpEntityPropertyChanges { get; set; }
        public virtual DbSet<AbpFeature> AbpFeatures { get; set; }
        public virtual DbSet<AbpLanguage> AbpLanguages { get; set; }
        public virtual DbSet<AbpLanguageText> AbpLanguageTexts { get; set; }
        public virtual DbSet<AbpNotification> AbpNotifications { get; set; }
        public virtual DbSet<AbpNotificationSubscription> AbpNotificationSubscriptions { get; set; }
        public virtual DbSet<AbpOrganizationUnitRole> AbpOrganizationUnitRoles { get; set; }
        public virtual DbSet<AbpOrganizationUnit> AbpOrganizationUnits { get; set; }
        public virtual DbSet<AbpPermission> AbpPermissions { get; set; }
        public virtual DbSet<AbpPersistedGrant> AbpPersistedGrants { get; set; }
        public virtual DbSet<AbpRoleClaim> AbpRoleClaims { get; set; }
        public virtual DbSet<AbpRole> AbpRoles { get; set; }
        public virtual DbSet<AbpSetting> AbpSettings { get; set; }
        public virtual DbSet<AbpTenantNotification> AbpTenantNotifications { get; set; }
        public virtual DbSet<AbpTenant> AbpTenants { get; set; }
        public virtual DbSet<AbpUserAccount> AbpUserAccounts { get; set; }
        public virtual DbSet<AbpUserClaim> AbpUserClaims { get; set; }
        public virtual DbSet<AbpUserLoginAttempt> AbpUserLoginAttempts { get; set; }
        public virtual DbSet<AbpUserLogin> AbpUserLogins { get; set; }
        public virtual DbSet<AbpUserNotification> AbpUserNotifications { get; set; }
        public virtual DbSet<AbpUserOrganizationUnit> AbpUserOrganizationUnits { get; set; }
        public virtual DbSet<AbpUserRole> AbpUserRoles { get; set; }
        public virtual DbSet<AbpUser> AbpUsers { get; set; }
        public virtual DbSet<AbpUserToken> AbpUserTokens { get; set; }
        public virtual DbSet<AbpWebhookEvent> AbpWebhookEvents { get; set; }
        public virtual DbSet<AbpWebhookSendAttempt> AbpWebhookSendAttempts { get; set; }
        public virtual DbSet<AbpWebhookSubscription> AbpWebhookSubscriptions { get; set; }
        public virtual DbSet<AlarmHistory> AlarmHistories { get; set; }
        public virtual DbSet<AppBinaryObject> AppBinaryObjects { get; set; }
        public virtual DbSet<AppChatMessage> AppChatMessages { get; set; }
        public virtual DbSet<AppFriendship> AppFriendships { get; set; }
        public virtual DbSet<AppInvoice> AppInvoices { get; set; }
        public virtual DbSet<AppModemConfig> AppModemConfigs { get; set; }
        public virtual DbSet<AppSubscriptionPayment> AppSubscriptionPayments { get; set; }
        public virtual DbSet<AppSubscriptionPaymentsExtensionData> AppSubscriptionPaymentsExtensionDatas { get; set; }
        public virtual DbSet<Bank> Banks { get; set; }
        public virtual DbSet<BuyCardPriorityConfig> BuyCardPriorityConfigs { get; set; }
        public virtual DbSet<BuyPincodeTransaction> BuyPincodeTransactions { get; set; }
        public virtual DbSet<BuyPincodeTransactionDetail> BuyPincodeTransactionDetails { get; set; }
        public virtual DbSet<CaptchaFile> CaptchaFiles { get; set; }
        public virtual DbSet<ChargingPartnerProviderConfig> ChargingPartnerProviderConfigs { get; set; }
        public virtual DbSet<ChargingTopupTransaction> ChargingTopupTransactions { get; set; }
        public virtual DbSet<ChargingTopupTransactionHistory> ChargingTopupTransactionHistories { get; set; }
        public virtual DbSet<ChargingTransaction> ChargingTransactions { get; set; }
        public virtual DbSet<ChargingTransactionCallbackPartnerHistory> ChargingTransactionCallbackPartnerHistories { get; set; }
        public virtual DbSet<DepositInvoice> DepositInvoices { get; set; }
        public virtual DbSet<DepositPartnerInvoice> DepositPartnerInvoices { get; set; }
        public virtual DbSet<DiscountPolicy> DiscountPolicies { get; set; }
        public virtual DbSet<GenChargingInvoice> GenChargingInvoices { get; set; }
        public virtual DbSet<GenInvoice> GenInvoices { get; set; }
        public virtual DbSet<Group> Groups { get; set; }
        public virtual DbSet<GroupPermission> GroupPermissions { get; set; }
        public virtual DbSet<InvoiceDiscountHistory> InvoiceDiscountHistories { get; set; }
        public virtual DbSet<InvoiceTypeTelcoChargingConfig> InvoiceTypeTelcoChargingConfigs { get; set; }
        public virtual DbSet<MaintainSM> MaintainSMS { get; set; }
        public virtual DbSet<MaintenanceSm> MaintenanceSms { get; set; }
        public virtual DbSet<MerchantUserDepositTransaction> MerchantUserDepositTransactions { get; set; }
        public virtual DbSet<MobiFoneToken> MobiFoneTokens { get; set; }
        public virtual DbSet<ModemChargingActiveSimHistory> ModemChargingActiveSimHistories { get; set; }
        public virtual DbSet<NotificationText> NotificationTexts { get; set; }
        public virtual DbSet<Partner> Partners { get; set; }
        public virtual DbSet<PartnerBalance> PartnerBalances { get; set; }
        public virtual DbSet<PartnerBalanceHistory> PartnerBalanceHistories { get; set; }
        public virtual DbSet<PartnerChargingPartnerTopupConfig> PartnerChargingPartnerTopupConfigs { get; set; }
        public virtual DbSet<PartnerDiscountPolicy> PartnerDiscountPolicies { get; set; }
        public virtual DbSet<PartnerServiceConfig> PartnerServiceConfigs { get; set; }
        public virtual DbSet<PartnerServiceWorkerChannelConfig> PartnerServiceWorkerChannelConfigs { get; set; }
        public virtual DbSet<PartnerTopupTransactionConfigMaxWaiting> PartnerTopupTransactionConfigMaxWaitings { get; set; }
        public virtual DbSet<PartnerTransaction> PartnerTransactions { get; set; }
        public virtual DbSet<PartnerUser> PartnerUsers { get; set; }
        public virtual DbSet<PartnerUserPartner> PartnerUserPartners { get; set; }
        public virtual DbSet<PartnerUserProvider> PartnerUserProviders { get; set; }
        public virtual DbSet<Permission> Permissions { get; set; }
        public virtual DbSet<PinCodeStock> PinCodeStocks { get; set; }
        public virtual DbSet<Product> Products { get; set; }
        public virtual DbSet<Rpt_BusinessReport> Rpt_BusinessReport { get; set; }
        public virtual DbSet<Rpt_CustomerBalanceByDate> Rpt_CustomerBalanceByDate { get; set; }
        public virtual DbSet<Rpt_CustomerBalanceDetailByDate> Rpt_CustomerBalanceDetailByDate { get; set; }
        public virtual DbSet<Rpt_CustomerDebit> Rpt_CustomerDebit { get; set; }
        public virtual DbSet<Rpt_SystemMoneyByDay> Rpt_SystemMoneyByDay { get; set; }
        public virtual DbSet<SaleInvoice> SaleInvoices { get; set; }
        public virtual DbSet<SaleInvoiceBuyPincodeDetail> SaleInvoiceBuyPincodeDetails { get; set; }
        public virtual DbSet<SaleInvoiceCalculationHistory> SaleInvoiceCalculationHistories { get; set; }
        public virtual DbSet<SaleInvoiceTopupDetail> SaleInvoiceTopupDetails { get; set; }
        public virtual DbSet<ServiceProvider> ServiceProviders { get; set; }
        public virtual DbSet<ServiceProviderConfig> ServiceProviderConfigs { get; set; }
        public virtual DbSet<ServiceProviderDiscountPolicy> ServiceProviderDiscountPolicies { get; set; }
        public virtual DbSet<Service> Services { get; set; }
        public virtual DbSet<SIM> SIMs { get; set; }
        public virtual DbSet<SimAccount> SimAccounts { get; set; }
        public virtual DbSet<SimAccountInfo> SimAccountInfoes { get; set; }
        public virtual DbSet<SMSList> SMSLists { get; set; }
        public virtual DbSet<SourceMoney> SourceMoneys { get; set; }
        public virtual DbSet<SubscriberChannelAuthentication> SubscriberChannelAuthentications { get; set; }
        public virtual DbSet<SystemAccount> SystemAccounts { get; set; }
        public virtual DbSet<SystemSetting> SystemSettings { get; set; }
        public virtual DbSet<Telco> Telcoes { get; set; }
        public virtual DbSet<TelcoServicePaidType> TelcoServicePaidTypes { get; set; }
        public virtual DbSet<Temp_SimZP> Temp_SimZP { get; set; }
        public virtual DbSet<Ticket> Tickets { get; set; }
        public virtual DbSet<TicketType> TicketTypes { get; set; }
        public virtual DbSet<TopupDepositOrder> TopupDepositOrders { get; set; }
        public virtual DbSet<TopupOrder> TopupOrders { get; set; }
        public virtual DbSet<TopupOrderDepositAccount> TopupOrderDepositAccounts { get; set; }
        public virtual DbSet<TopupPartnerProviderConfig> TopupPartnerProviderConfigs { get; set; }
        public virtual DbSet<TopupPriorityConfig> TopupPriorityConfigs { get; set; }
        public virtual DbSet<TopupTransaction> TopupTransactions { get; set; }
        public virtual DbSet<Transaction> Transactions { get; set; }
        public virtual DbSet<TransferMoney> TransferMoneys { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<UserBalance> UserBalances { get; set; }
        public virtual DbSet<UserBalanceHistory> UserBalanceHistories { get; set; }
        public virtual DbSet<UserGroup> UserGroups { get; set; }
        public virtual DbSet<UserPartner> UserPartners { get; set; }
        public virtual DbSet<WorkerChannelTelcoPaidTypeConfig> WorkerChannelTelcoPaidTypeConfigs { get; set; }
        public virtual DbSet<WorkerServerConfig> WorkerServerConfigs { get; set; }
        public virtual DbSet<CheckCardTransaction> CheckCardTransactions { get; set; }
        public virtual DbSet<JobSchedule> JobSchedules { get; set; }
        public virtual DbSet<Rpt_CustomerDebitHistoryByDay> Rpt_CustomerDebitHistoryByDay { get; set; }
        public virtual DbSet<Rpt_CustomerDebitHistoryByDay_v2> Rpt_CustomerDebitHistoryByDay_v2 { get; set; }
    }
}
