//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BotTelegram.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rpt_CustomerBalanceDetailByDate
    {
        public long Id { get; set; }
        public System.DateTime ReportDate { get; set; }
        public System.DateTime CreationTime { get; set; }
        public System.DateTime LastModifiedTime { get; set; }
        public long UserId { get; set; }
        public decimal TotalOpeningBalance { get; set; }
        public decimal TotalClosingBalance { get; set; }
        public decimal TotalIncreasedBalance { get; set; }
        public decimal TotalDecreasedBalance { get; set; }
        public decimal IncreasedDeposit { get; set; }
        public decimal IncreasedRefundDiscount { get; set; }
        public decimal IncreasedRefund { get; set; }
        public decimal IncreasedTransfer { get; set; }
        public decimal DecreasedCustomerPaid { get; set; }
        public decimal DecreaseCashout { get; set; }
        public decimal DecreaseTransferMoney { get; set; }
        public Nullable<byte> BalanceType { get; set; }
    }
}
