//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BotTelegram.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rpt_CustomerDebit
    {
        public int Id { get; set; }
        public System.DateTime ReportDate { get; set; }
        public System.DateTime CreationTime { get; set; }
        public System.DateTime LastModifiedTime { get; set; }
        public Nullable<long> UserId { get; set; }
        public Nullable<decimal> OpeningAmount { get; set; }
        public Nullable<decimal> ClosingAmount { get; set; }
        public Nullable<decimal> TotalSuccessAmount { get; set; }
        public Nullable<decimal> TotalCancelAmount { get; set; }
        public Nullable<decimal> TotalPaidAmount { get; set; }
    }
}
