//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BotTelegram.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rpt_BusinessReport
    {
        public int Id { get; set; }
        public System.DateTime ReportDate { get; set; }
        public System.DateTime CreationTime { get; set; }
        public System.DateTime LastModifiedTime { get; set; }
        public string PartnerCode { get; set; }
        public string ProviderCode { get; set; }
        public decimal TotalAmount { get; set; }
        public decimal CostAmount { get; set; }
        public decimal SaleAmount { get; set; }
        public decimal TempProfitAmount { get; set; }
        public Nullable<int> TotalTran { get; set; }
        public byte CardType { get; set; }
    }
}
