//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BotTelegram.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rpt_CustomerDebitHistoryByDay_v2
    {
        public Nullable<System.DateTime> ReportDate { get; set; }
        public long UserId { get; set; }
        public string User_ { get; set; }
        public string ParentUser_ { get; set; }
        public decimal OpeningDebit { get; set; }
        public decimal OpeningBalance { get; set; }
        public decimal TotalInvoiceUnprocess { get; set; }
        public decimal TotalSuccess { get; set; }
        public decimal TotalRefund { get; set; }
        public Nullable<decimal> UnprocessAmount { get; set; }
        public Nullable<decimal> Diff { get; set; }
        public System.DateTime CreatedTime { get; set; }
    }
}
