//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BotTelegram.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ServiceProvider
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Code { get; set; }
        public string Password { get; set; }
        public string Phone { get; set; }
        public Nullable<short> Status { get; set; }
        public string ClientTokenApi { get; set; }
        public string ClientSignature { get; set; }
        public string ClientCodeRequest { get; set; }
        public string ApiUrl { get; set; }
        public bool IsEnableChargingTopup { get; set; }
        public bool IsEnableCharging { get; set; }
        public int ChargingTopupPriority { get; set; }
        public int ChargingPriority { get; set; }
        public string ViettelPrepaidServiceCode { get; set; }
        public string ViettelPostpaidServiceCode { get; set; }
        public string ChargingTelegramSupportGroupId { get; set; }
        public string TopupTelegramSupportGroupId { get; set; }
        public Nullable<int> TenantId { get; set; }
        public System.DateTime CreationTime { get; set; }
        public Nullable<long> CreatorUserId { get; set; }
        public Nullable<System.DateTime> LastModificationTime { get; set; }
        public Nullable<long> LastModifierUserId { get; set; }
    }
}
