//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BotTelegram.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class SIM
    {
        public int ID { get; set; }
        public string IMSI { get; set; }
        public string SimNo { get; set; }
        public string SimID { get; set; }
        public string SimRole { get; set; }
        public string AccountName { get; set; }
        public string BCCSPassword { get; set; }
        public string BankPlusPassword { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<System.DateTime> LastUpdate { get; set; }
        public Nullable<decimal> BCCSBalance { get; set; }
        public Nullable<System.DateTime> BCCSBalanceUpdateTime { get; set; }
        public Nullable<decimal> MBBalance { get; set; }
        public Nullable<System.DateTime> MBBalanceUpdateTime { get; set; }
        public string RunningWorker { get; set; }
        public string CurrentState { get; set; }
        public Nullable<int> Priority { get; set; }
        public Nullable<bool> IsWaitingOtp { get; set; }
        public Nullable<System.DateTime> LastTopupTime { get; set; }
        public string GSMServer { get; set; }
        public Nullable<System.DateTime> GSMUpdate { get; set; }
        public Nullable<short> ChargingStatus { get; set; }
        public Nullable<bool> IsLimitedDayVT136 { get; set; }
        public Nullable<bool> IsLimitedDayVT199 { get; set; }
        public Nullable<System.DateTime> TimeLimitedDayVT136 { get; set; }
        public Nullable<System.DateTime> TimeLimitedDayVT199 { get; set; }
        public Nullable<int> AvaiableInDayVT136 { get; set; }
        public Nullable<int> AvaiableInDayVT119 { get; set; }
        public Nullable<int> TenantId { get; set; }
        public System.DateTime CreationTime { get; set; }
        public Nullable<long> CreatorUserId { get; set; }
        public Nullable<System.DateTime> LastModificationTime { get; set; }
        public Nullable<long> LastModifierUserId { get; set; }
        public Nullable<System.DateTime> MyViettelLastUpdate { get; set; }
        public Nullable<bool> IsLimitedDayMyViettel { get; set; }
        public Nullable<System.DateTime> TimeLimitedDayMyViettel { get; set; }
        public Nullable<bool> IsEnableMyViettel { get; set; }
        public Nullable<bool> CanUseUssd136 { get; set; }
        public Nullable<int> MyViettelChargedInDay { get; set; }
        public Nullable<int> MyViettelCheckCardInDay { get; set; }
        public string MyViettelWorkerServer { get; set; }
        public string Note { get; set; }
        public Nullable<System.DateTime> CreatedTime { get; set; }
        public Nullable<bool> IsEnableMyViettelChargeCard { get; set; }
        public Nullable<bool> IsEnableMyViettelCheckCard { get; set; }
        public Nullable<bool> IsLimitMyViettelChargeCardInDay { get; set; }
        public Nullable<System.DateTime> TimeLimitMyViettelChargeCardInDay { get; set; }
        public Nullable<bool> IsLimitMyViettelCheckCardInday { get; set; }
        public Nullable<System.DateTime> TimeLimitMyViettelCheckCardInday { get; set; }
        public Nullable<bool> IsForceLoginMyViettel { get; set; }
        public Nullable<int> MyViettelMaxCountChargeInDay { get; set; }
        public Nullable<bool> MyViettelIsGetAccInfo { get; set; }
        public Nullable<System.DateTime> NextLoginTime { get; set; }
    }
}
