//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BotTelegram.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class SimAccountInfo
    {
        public int Id { get; set; }
        public string SimNo { get; set; }
        public Nullable<decimal> cuoc_phat_sinh { get; set; }
        public Nullable<decimal> da_thanh_toan { get; set; }
        public Nullable<decimal> no_con_lai { get; set; }
        public Nullable<decimal> no_cuoc_cuoi_ky { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public string Info { get; set; }
        public Nullable<decimal> tai_khoan_chinh { get; set; }
    }
}
