//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BotTelegram.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class SourceMoney
    {
        public int Id { get; set; }
        public string SourceMoneyName { get; set; }
        public string AccountNo { get; set; }
        public string AccountName { get; set; }
        public Nullable<byte> Status { get; set; }
        public long SystemAccountId { get; set; }
    }
}
