//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BotTelegram.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class SubscriberChannelAuthentication
    {
        public int Id { get; set; }
        public string ChannelCode { get; set; }
        public string Subscriber { get; set; }
        public string Password { get; set; }
        public Nullable<byte> Status { get; set; }
        public Nullable<System.DateTime> CreatedTime { get; set; }
        public string WorkerServer { get; set; }
        public string WorkerId { get; set; }
        public string CurrentState { get; set; }
        public Nullable<System.DateTime> LastUpdatedTime { get; set; }
        public string AuthenticationData { get; set; }
        public Nullable<int> RetryCount { get; set; }
        public Nullable<System.DateTime> NextProcessTime { get; set; }
    }
}
