//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BotTelegram.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TopupOrder
    {
        public long Id { get; set; }
        public string OrderCode { get; set; }
        public Nullable<long> UserId { get; set; }
        public string SessionId { get; set; }
        public int Telco { get; set; }
        public byte PaidType { get; set; }
        public string PhoneNumber { get; set; }
        public int Amount { get; set; }
        public int ChargedAmount { get; set; }
        public double Discount { get; set; }
        public decimal SaleAmount { get; set; }
        public System.DateTime CreatedTime { get; set; }
        public byte Status { get; set; }
        public System.DateTime LastUpdated { get; set; }
        public Nullable<long> TopupDepositId { get; set; }
        public string MyPassword { get; set; }
        public Nullable<long> SaleInvoiceId { get; set; }
        public Nullable<int> SourceId { get; set; }
        public string AccountNo { get; set; }
        public string AccountName { get; set; }
        public Nullable<long> VoucherId { get; set; }
        public Nullable<decimal> VoucherAmount { get; set; }
        public string VoucherCode { get; set; }
        public string ClientIP { get; set; }
    }
}
