//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BotTelegram.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TopupPriorityConfig
    {
        public int Id { get; set; }
        public int TelcoId { get; set; }
        public int FromAmount { get; set; }
        public int ToAmount { get; set; }
        public byte PaidType { get; set; }
        public string ProviderCode { get; set; }
        public byte Priority { get; set; }
        public double Discount { get; set; }
        public byte Status { get; set; }
    }
}
