//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BotTelegram.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TopupTransaction
    {
        public long Id { get; set; }
        public string InvoiceCode { get; set; }
        public Nullable<byte> InvoiceType { get; set; }
        public string TransCode { get; set; }
        public Nullable<System.DateTime> CreatedTime { get; set; }
        public string Mobile { get; set; }
        public Nullable<int> ProductId { get; set; }
        public Nullable<byte> TelcoId { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public Nullable<byte> PaidType { get; set; }
        public Nullable<byte> ServiceType { get; set; }
        public Nullable<bool> IsSplitAmount { get; set; }
        public string RequestIpAddress { get; set; }
        public Nullable<byte> Status { get; set; }
        public string PartnerCode { get; set; }
        public Nullable<int> PartnerDiscountPolicyId { get; set; }
        public Nullable<decimal> PartnerDiscountPolicyDiscountPercentage { get; set; }
        public Nullable<decimal> PartnerSaleAmount { get; set; }
        public Nullable<bool> IsCallbackPartner { get; set; }
        public Nullable<System.DateTime> CallbackTime { get; set; }
        public string ProviderCode { get; set; }
        public Nullable<int> ProviderDiscountPolicyId { get; set; }
        public Nullable<decimal> ProviderDiscountPolicyDiscountPercentage { get; set; }
        public Nullable<decimal> ProviderPartnerSaleAmount { get; set; }
        public string ProviderRequestTransCode { get; set; }
        public string ProviderResponseTransCode { get; set; }
        public string ProviderResponseCode { get; set; }
        public string ProviderResponseMessage { get; set; }
        public Nullable<System.DateTime> ProviderCallbackTime { get; set; }
        public Nullable<decimal> ProviderResponseChargedAmount { get; set; }
        public Nullable<bool> IsReCalculate { get; set; }
        public Nullable<int> CancelTransactionInSecond { get; set; }
        public Nullable<bool> IsAlowExtend { get; set; }
        public Nullable<int> ExtendTimeInSec { get; set; }
        public Nullable<int> MinCardValue { get; set; }
        public Nullable<bool> IsExcuteExtend { get; set; }
        public bool IsEnableChangeProvider { get; set; }
        public string ChangeToProvider { get; set; }
        public int ChangeProviderTimeInSecond { get; set; }
        public bool IsExcuteChangeProvider { get; set; }
        public int Priority { get; set; }
        public Nullable<System.DateTime> PartnerLastCheckTime { get; set; }
        public string PartnerLastCheckResponse { get; set; }
        public Nullable<long> UserId { get; set; }
        public Nullable<long> LastChargingTranId { get; set; }
    }
}
