//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BotTelegram.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TopupOrderDepositAccount
    {
        public int Id { get; set; }
        public int SourceMoneyId { get; set; }
        public string AccountNo { get; set; }
        public string AccountName { get; set; }
        public int Status { get; set; }
    }
}
