//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BotTelegram.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class WorkerServerConfig
    {
        public int Id { get; set; }
        public string WorkerChannelCode { get; set; }
        public string WorkerServer { get; set; }
        public string CurrentState { get; set; }
        public Nullable<System.DateTime> LastUpdateTime { get; set; }
        public string NordVPNGroup { get; set; }
        public string Note { get; set; }
        public Nullable<bool> IsGetCaptchaFisrt { get; set; }
        public Nullable<int> DelayTimeInSec { get; set; }
        public string CaptchaProvider { get; set; }
    }
}
